# Generated by Django 4.2.2 on 2023-09-23 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_device_remove_firmwareupdate_batteryvalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmware_version', models.CharField(max_length=20)),
                ('firmware_version_file', models.FileField(upload_to='firmware/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='firmwareupdate',
            name='firmware_version',
        ),
        migrations.RemoveField(
            model_name='firmwareupdate',
            name='firmware_version_file',
        ),
        migrations.RemoveField(
            model_name='firmwareupdatehistory',
            name='firmware_version',
        ),
        migrations.RemoveField(
            model_name='firmwareupdatehistory',
            name='firmware_version_file',
        ),
        migrations.AddField(
            model_name='firmwareupdate',
            name='firmware',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apiapp.firmware'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firmwareupdatehistory',
            name='firmware',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apiapp.firmware'),
            preserve_default=False,
        ),
    ]
