# Generated by Django 4.2.2 on 2023-09-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_firmware_remove_firmwareupdate_firmware_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmware',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
