# Generated by Django 4.2.2 on 2023-09-23 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_firmware_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmware',
            name='number',
        ),
    ]
