# Generated by Django 4.2.2 on 2023-09-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_remove_firmware_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='channel_id',
            field=models.CharField(default='Channel ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(default='Device Name', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='firmware_version',
            field=models.CharField(default='Firmware Version', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='firmware_version_file',
            field=models.FileField(null=True, upload_to='firmware/'),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='uploaded_at',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='firmwareupdate',
            name='confrigDownload',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='firmwareupdate',
            name='fileDownload',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='firmwareupdate',
            name='spvValue',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='firmwareupdate',
            name='syncState',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='firmwareupdatehistory',
            name='confrigDownload',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='firmwareupdatehistory',
            name='fileDownload',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='firmwareupdatehistory',
            name='history_date',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='firmwareupdatehistory',
            name='spvValue',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='firmwareupdatehistory',
            name='syncState',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='firmwareupdatehistory',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
