# Generated by Django 4.2.2 on 2023-09-23 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_alter_device_channel_id_alter_device_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwareUpdateStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileDownload', models.IntegerField(default=0, null=True)),
                ('spvValue', models.PositiveIntegerField(default=0, null=True)),
                ('syncState', models.IntegerField(default=0, null=True)),
                ('confrigDownload', models.IntegerField(default=0, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('device_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.device')),
                ('firmware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.firmware')),
            ],
        ),
    ]
