# Generated by Django 4.2.2 on 2023-09-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0007_firmwareupdatestats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirmwareUpdateStats',
        ),
    ]
