# Generated by Django 4.2.2 on 2023-10-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0008_delete_firmwareupdatestats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(default='Field Name', max_length=50, null=True)),
                ('field_value', models.CharField(default='Field Value', max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='firmwareupdate',
            name='confrigDownload',
        ),
        migrations.RemoveField(
            model_name='firmwareupdate',
            name='fileDownload',
        ),
        migrations.RemoveField(
            model_name='firmwareupdate',
            name='spvValue',
        ),
        migrations.RemoveField(
            model_name='firmwareupdate',
            name='syncState',
        ),
        migrations.AddField(
            model_name='firmwareupdate',
            name='field',
            field=models.ManyToManyField(to='apiapp.fields'),
        ),
    ]
