# Generated by Django 4.2.2 on 2023-10-02 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0009_fields_remove_firmwareupdate_confrigdownload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fields',
            name='field_value',
        ),
        migrations.RemoveField(
            model_name='firmwareupdate',
            name='field',
        ),
        migrations.AlterField(
            model_name='fields',
            name='field_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='FirmwareUpdateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.fields')),
                ('firmware_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.firmwareupdate')),
            ],
        ),
        migrations.AddField(
            model_name='firmwareupdate',
            name='fields',
            field=models.ManyToManyField(through='apiapp.FirmwareUpdateField', to='apiapp.fields'),
        ),
    ]
