# Generated by Django 4.2.2 on 2023-10-02 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0010_remove_fields_field_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmwareupdate',
            name='fields',
            field=models.ManyToManyField(through='apiapp.FirmwareUpdateField', to='apiapp.fields', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
