# Generated by Django 4.2.2 on 2023-10-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0012_alter_firmwareupdate_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='fields',
            name='edit',
            field=models.BooleanField(default=False),
        ),
    ]
