# Generated by Django 4.2.2 on 2023-12-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0017_alter_device_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmware',
            name='firmwareversionfile',
            field=models.BinaryField(null=True),
        ),
    ]
