# Generated by Django 4.2.2 on 2024-01-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0017_alter_device_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmware',
            name='firmware_version',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
