# Generated by Django 4.2.2 on 2023-12-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0018_firmware_firmwareversionfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firmware',
            old_name='firmwareversionfile',
            new_name='gibsonexp',
        ),
    ]
