# Generated by Django 4.2.2 on 2023-12-14 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0020_firm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Firm',
        ),
        migrations.RenameField(
            model_name='firmware',
            old_name='gibsonexp',
            new_name='firmware_version_content',
        ),
        migrations.RemoveField(
            model_name='firmware',
            name='firmware_version_file',
        ),
    ]
